# Generated by Django 5.0.7 on 2024-07-14 12:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transfer", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accounts",
            old_name="uiid",
            new_name="uuid",
        ),
    ]
