# Generated by Django 5.0.7 on 2024-07-15 11:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transfer", "0002_rename_uiid_accounts_uuid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accounts",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["at"]},
        ),
    ]
