# Generated by Django 5.0.7 on 2024-07-17 17:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transfer", "0003_alter_accounts_options_alter_transaction_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-at"]},
        ),
    ]
